apiVersion: v1
kind: ServiceAccount
metadata:
  name: kasten-alerting
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kasten-alerting.labels" . | nindent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
